# ===============================================================
# 🛡️ PhishGuard - Export Tier 1 model to JSON for on-device JS
# ===============================================================
# The Tier 1 pipeline is a char-ngram TF-IDF + Logistic Regression -- a
# LINEAR model. That means it can be replicated exactly in the browser with
# a small weights table and ~60 lines of JS (no ONNX runtime needed). This
# script dumps everything the JS scorer needs: per-ngram (idf, coef), the
# intercept, and the vectorizer config.
#
# Run:  python export_model.py   ->  ../Extension/model.json
# ===============================================================

from __future__ import annotations

import json
from pathlib import Path

import joblib

HERE = Path(__file__).parent
MODEL = HERE / "classifier.joblib"
OUT = HERE.parent / "Extension" / "model.json"


def main() -> None:
    pipe = joblib.load(MODEL)
    vec = pipe.named_steps["tfidf"]
    clf = pipe.named_steps["clf"]

    idf = vec.idf_
    coef = clf.coef_[0]
    # Per ngram: [idf, coef]. JS needs idf (for the L2 norm) and coef (for the
    # dot product). Rounded to keep the file small without changing the verdict.
    terms = {
        ng: [round(float(idf[idx]), 5), round(float(coef[idx]), 5)]
        for ng, idx in vec.vocabulary_.items()
    }

    out = {
        "ngram_range": list(vec.ngram_range),
        "sublinear_tf": bool(vec.sublinear_tf),
        "norm": vec.norm,
        "lowercase": bool(vec.lowercase),
        "intercept": float(clf.intercept_[0]),
        "classes": [int(c) for c in clf.classes_],
        "terms": terms,
    }

    payload = json.dumps(out, ensure_ascii=False)
    OUT.write_text(payload, encoding="utf-8")

    # Also emit a content-script-loadable global so the extension needs no
    # fetch / web_accessible_resources / async load — just include it first.
    js = OUT.parent / "model-data.js"
    js.write_text(
        "// AUTO-GENERATED by Model/export_model.py — do not edit by hand.\n"
        "globalThis.PHISHGUARD_MODEL = " + payload + ";\n",
        encoding="utf-8",
    )

    print(f"Exported {len(terms)} ngrams -> {OUT.name} "
          f"({OUT.stat().st_size / 1024:.0f} KB) + {js.name}")


if __name__ == "__main__":
    main()
